extends:
  - 'standard-with-typescript'
  - 'plugin:jsdoc/recommended'

parserOptions:
  project: './tsconfig.eslint.json'

overrides:
  - files: 'test/**/*'
    env:
      mocha: true
    rules:
      no-unused-expressions: off
      '@typescript-eslint/no-unused-expressions': off
      '@typescript-eslint/no-floating-promises': off
